# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    default_config: base_config
    configs:
        base_config:
            toolbar: full
#                - { name: "styles", items: [ 'Bold','Italic', 'Link' ] }
